function(torrentutils_set_project_warnings target_name)
    if(MSVC)
        set(project_warnings /W4 /permissive- /utf-8)
        if(TORRENTUTILS_WARNINGS_AS_ERRORS)
            list(APPEND project_warnings /WX)
        endif()
    else()
        set(project_warnings -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
        if(TORRENTUTILS_WARNINGS_AS_ERRORS)
            list(APPEND project_warnings -Werror)
        endif()
    endif()

    target_compile_options(${target_name} PRIVATE ${project_warnings})
endfunction()
